# Site settings
title: RCode
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  vasylhupka/vasylhupka.github.io

# Build settings
markdown: kramdown
